### ISSUE TITLE
How to preselect location on edit

### ISSUE THREAD

**Issue by bernhardh** [naifalshaye/nova-map-address#2]
How to prefil the map with model coordinates/address?

**Comment by naifalshaye** [comment]
When you add a marker it get the latitude and longitude and geo reverse it to get the full street address and that what is saved.

**Comment by bernhardh** [comment]
That doesn't answer my question. In you documentation:

```
 MapAddress::make('address')
    ->initLocation(38.4350,122.6894)
    ->zoom(12),
```

you hardcode set the initLocation to some coordinates and zoom level. But how to set the coordinate by model data? Something like this:

```
 MapAddress::make('address')
    ->setLat("lat")
    ->setLng("lng")
    ->setZoom('zoom'),
```

and then it takes the data form the model. So how can we do this?

**Comment by naifalshaye** [comment]
Package updated, now marker will be visible in edit page.

**Comment by naifalshaye** [comment]
Package updated, now marker will be visible in edit page.
