### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: o[1] is undefined"

### ISSUE THREAD

**Issue by Dontorpedo** [naifalshaye/nova-map-address#6]
Hello,

there is an error, and the map is grey.

error is in the subject.

thanks 
D

**Comment by naifalshaye** [comment]
Hi,
Make sure you do the below:

Publish config file 
php artisan vendor:publish --provider="Naif\MapAddress\FieldServiceProvider"

Add your api key to .env file
MAP_ADDRESS_API_KEY=

**Comment by Dontorpedo** [comment]
yeah i did alleready, but no change :(

**Comment by naifalshaye** [comment]
Make sure you have enabled "Maps JavaScript API" library in Google API for the provided API KEY.

**Comment by Dontorpedo** [comment]
i tried to prefill the field with a adress like

MapAddress::make('Map', 'street')

this gave the error.. so solved
