### ISSUE TITLE
Can't install in Laravel 6.0

### ISSUE THREAD

**Issue by JMoralSquare1** [naifalshaye/nova-map-address#8]
Hi!

This package can't be install in Laravel 6.0, any update about it?

Thanks!!

**Comment by KnowledgeWanderer** [comment]
any updates?

**Comment by KnowledgeWanderer** [comment]
@naifalshaye help us

**Comment by MammutAlex** [comment]
@JMoralSquare1 @KnowledgeWanderer I created pull request for support laravel 6
For use package now you can install my [fork](https://github.com/MammutAlex/nova-map-address)
`composer require mammut-alex/map_address:dev-master`

**Comment by naifalshaye** [comment]
Done, you can install it now thanks to @MammutAlex

**Comment by tnup** [comment]
you need to publish a new version in order to install it without :dev-master.
